CREATE ROLE projectname;
ALTER ROLE projectname WITH LOGIN PASSWORD 'projectname' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE projectname OWNER projectname;
REVOKE ALL ON DATABASE projectname FROM PUBLIC;
GRANT CONNECT ON DATABASE projectname TO projectname;
GRANT ALL ON DATABASE projectname TO projectname;